/* =========================================================================
   Pole Position — first-install seed dataset.
   This is the STARTING DATA SET, loaded the very first time the app is
   installed (when localStorage is empty). It was extracted out of index.html
   so the data lives separately from the UI/logic: edit Ben's starting leads,
   tasks and contacts here without touching the app code.

   Pure data, zero DOM, zero deps. Attaches to window.PP_SEED in the browser
   AND exports for Node (so tests can validate it). The loader in index.html
   (`seed()`) wraps each record with { updatedAt, deleted } and resolves the
   relative-date convention below.

   Conventions:
   - `id` is a STABLE, deterministic seed id (e.g. "seed-lead-..."). Identical
     on every device so a first-time sync MERGES the seed instead of duplicating
     it. Never change an id once shipped. The jobs feed reuses these ids too.
   - Dates (`nextDue` on leads, `due` on tasks): a value like "+5" means "5 days
     after install"; an ISO value like "2026-07-12" is an absolute deadline; ""
     means no date. Relative offsets keep a fresh install's near-term dates sane.
   - `hotness` is explicit per lead: "hot" (F1/racing/motorsport), "medium"
     (premium/cool brand), "normal" (standard garage).
   - Lead role titles + notes are intentionally kept in German (the original
     posting language). Task titles/notes are English (the default UI language).
   ========================================================================= */
(function () {
  "use strict";

  const SEED = {
    // Real open positions from the June 2026 research, closest first. Links verified
    // live on 2026-06-27; re-checked 2026-07-30 (dead postings removed, stale
    // motorsport links re-pointed) — each points at the actual job posting (deep link).
    leads: [
      // --- Merbag (current employer — START HERE, lowest-friction internal move) ---
      // (The Zollikon Fachmann/Mechatroniker posting closed — removed 2026-07-30.)
      {
        id: "seed-lead-merbag-diag-schlieren",
        company: "Merbag — Schlieren",
        role: "Automobil-Diagnostiker/Systemtechniker Transporter 100% (m/w)",
        link: "https://www.jobs.ch/en/vacancies/detail/9be31b95-ecee-4b83-9186-41e8043a0ec3/",
        location: "Schlieren, ZH — ~10 Min",
        salary: "CHF 5'500–6'000 / Mt (Ziel)",
        source: "jobs.ch / Merbag",
        favourite: false,
        priority: 4,
        stage: "researching",
        hotness: "medium",
        nextAction: "Bewerben — 4-Monats-Diagnostik-Stint + Xentry hervorheben",
        nextDue: "",
        contacts: ["seed-contact-gut"],
        notes: "Diagnostiker-Rolle bei Merbag — spielt direkt auf den Diagnostik-Stint und die Diagnostiker-Laufbahn (eidg. FA). Transporter, nicht PW.",
      },
      {
        id: "seed-lead-merbag-schlieren-nfz",
        company: "Merbag — Schlieren",
        role: "Automobil-Mechatroniker/-Fachmann Nutzfahrzeuge 100% (m/w)",
        link: "https://jobs.merbag.com/Automobil-Mechatroniker-Fachmann-Nutzfahrzeuge-100-mw-de-j362.html",
        location: "Schlieren, ZH — ~10 Min",
        salary: "",
        source: "Merbag careers",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "medium",
        nextAction: "Prüfen — Nutzfahrzeuge statt PW, intern via Herr Gut",
        nextDue: "",
        contacts: ["seed-contact-gut"],
        notes: "Merbag-Standort Schlieren. Nutzfahrzeuge (nicht PW) — als interner Wechsel trotzdem stark. Diagnostik/Xentry zählt.",
      },
      {
        id: "seed-lead-merbag-lastwagen",
        company: "Merbag — Zürich",
        role: "Automobil-Fachmann/-Mechatroniker Lastwagen 100% (m/w)",
        link: "https://jobs.merbag.com/Automobil-Fachmann-Mechatroniker-Lastwagen-100-mw-de-j792.html",
        location: "Zürich — ~10 Min",
        salary: "",
        source: "Merbag careers",
        favourite: false,
        priority: 2,
        stage: "researching",
        hotness: "medium",
        nextAction: "Option Lastwagen prüfen — falls PW-Stelle nicht klappt",
        nextDue: "",
        contacts: ["seed-contact-gut"],
        notes: "Lastwagen-Bereich. Eher Backup, da Ben aus dem PW-/AMG-Bereich kommt. Bei Merbag bleiben = geringste Reibung.",
      },
      {
        id: "seed-lead-amag-porsche-zh",
        company: "AMAG — Porsche Zentrum Zürich",
        role: "Automobil-Mechatroniker Porsche (m/w/d) 80–100%",
        link: "https://jobs.amag-group.ch/Automobil-Mechatroniker-Porsche-mwd-80-100-de-j23042.html",
        location: "Zürich — ~10 Min",
        salary: "CHF 5'500–6'500 / Mt (Ziel)",
        source: "AMAG careers",
        favourite: true,
        priority: 5,
        stage: "researching",
        hotness: "medium",
        nextAction: "Dossier auf Porsche zuschneiden (HV-Zert. zuoberst)",
        nextDue: "+5",
        contacts: [],
        notes: "Premium-Sportwagen vor der Haustür. HV + AMG sind die Hebel. AMAG erlaubt Direktbewerbung (WhatsApp).",
      },
      {
        id: "seed-lead-amag-altstetten",
        company: "AMAG — Uster",
        role: "Automobil-Mechatroniker oder Diagnostiker & Stv. Werkstattleiter 80–100%",
        link: "https://jobs.amag-group.ch/Automobil-Mechatroniker-oder-Diagnostiker-Stv-Werkstattlei-de-j21284.html",
        location: "Uster, ZH — ~25 Min",
        salary: "",
        source: "AMAG careers",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "normal",
        nextAction: "Bewerben — Mechatroniker oder Diagnostiker",
        nextDue: "+6",
        contacts: [],
        notes: "Mechatroniker ODER Diagnostiker mit Stv.-Werkstattleiter-Perspektive. (Die Altstetten-Stelle aus der Recherche ist nicht mehr offen.)",
      },
      {
        id: "seed-lead-amag-porsche-schlieren",
        company: "AMAG — Dübendorf",
        role: "Automobil-Diagnostiker (m/w/d) 100%",
        link: "https://jobs.amag-group.ch/Automobil-Diagnostiker-mwd-100-de-j22963.html",
        location: "Dübendorf, ZH — ~12 Min",
        salary: "",
        source: "AMAG careers",
        favourite: false,
        priority: 4,
        stage: "researching",
        hotness: "normal",
        nextAction: "Bewerben — Diagnostik-Stint hervorheben",
        nextDue: "",
        contacts: [],
        notes: "Diagnostiker-Stelle — spielt direkt auf den 4-Monats-Diagnostik-Stint + Xentry. (Die Porsche-Diagnostiker-Stelle in Schlieren ist nicht mehr offen.)",
      },
      {
        id: "seed-lead-sauber-f1",
        company: "Sauber / Audi F1 — Hinwil",
        role: "Trainee / Future Race Team Mechanic (Car Assembly)",
        link: "https://www.audif1.com/en/careers",
        location: "Hinwil, ZH — ~35 Min",
        salary: "CHF 5'000–5'500 / Mt (Einstieg)",
        source: "audif1.com",
        favourite: true,
        priority: 5,
        stage: "researching",
        hotness: "hot",
        nextAction: "audif1.com/en/careers periodisch prüfen (Trainee-Intake 2027)",
        nextDue: "+7",
        contacts: [],
        notes: "Formel 1 vor der Haustür, fast perfekter Fit für Einsteiger. Trainee-Programm aktuell zu (Stand 07/2026) — kommt erfahrungsgemäss für den 2027er-Intake wieder. Karriereseite neu: audif1.com. Siehe Guide → Motorsport.",
      },
      {
        id: "seed-lead-sportec",
        company: "Sportec AG — Höri",
        role: "Automobil-Mechatroniker*in 100%",
        link: "https://www.jobs.ch/en/vacancies/detail/0d11a3c4-840c-49e9-afd1-5e7b9ac798ff/",
        location: "Höri, ZH — ~20 Min",
        salary: "CHF 5'000–6'650 / Mt",
        source: "Sportec / jobs.ch",
        favourite: true,
        priority: 4,
        stage: "researching",
        hotness: "hot",
        nextAction: "Bewerben VOR Frist 13. Juli 2026",
        nextDue: "2026-07-12",
        contacts: [],
        notes: "Porsche/Audi + eigene Motorsport- & Classic-Abteilung. Frist 13.07.2026!",
      },
      // (The Emil Frey Dübendorf Fachmann/Mechatroniker posting closed (410) — removed 2026-07-30.)
      {
        id: "seed-lead-emilfrey-diag",
        company: "Emil Frey — Altendorf",
        role: "Automobil-Diagnostiker/-in",
        link: "https://jobs.emilfrey.ch/Automobildiagnostikerin-de-j1725.html",
        location: "Altendorf, SZ — ~30 Min",
        salary: "",
        source: "Emil Frey careers",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "normal",
        nextAction: "Prüfen — Diagnostik-Stint passt direkt",
        nextDue: "",
        contacts: [],
        notes: "Diagnostiker-Stelle bei Emil Frey. Passt zum Diagnostik-Stint. (Die Au-Wädenswil Mercedes-Stelle ist geschlossen.)",
      },
      {
        id: "seed-lead-eugster",
        company: "Garage H.U. Eugster AG",
        role: "Automobil-Mechatroniker",
        link: "https://www.jobs.ch/en/vacancies/detail/29dc812d-539a-492e-8ae9-fc142b3e4818",
        location: "Zürich — ~10 Min",
        salary: "",
        source: "jobs.ch",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "normal",
        nextAction: "Inserat prüfen",
        nextDue: "",
        contacts: [],
        notes: "Stadtgarage, Mechatroniker-Stelle aktuell offen.",
      },
      {
        id: "seed-lead-kanton-zh",
        company: "Kanton Zürich (Fuhrpark)",
        role: "Automobilmechatroniker/-in 100%",
        link: "https://www.zh.ch/de/arbeiten-kanton-zuerich/offene-stellen.html",
        location: "Urdorf — ~12 Min",
        salary: "",
        source: "zh.ch",
        favourite: false,
        priority: 2,
        stage: "researching",
        hotness: "normal",
        nextAction: "Beim Kanton periodisch prüfen",
        nextDue: "",
        contacts: [],
        notes: "Öffentlicher Fuhrpark — stabile Option. Aktuell keine passende Stelle ausgeschrieben; periodisch prüfen.",
      },
      {
        id: "seed-lead-seegarage",
        company: "Seegarage Müller AG",
        role: "Automobilmechatroniker 80–100%",
        link: "https://www.seegarage-jobs.ch/jobdetails.php?key=0",
        location: "Horgen — ~22 Min",
        salary: "",
        source: "seegarage-jobs.ch",
        favourite: false,
        priority: 2,
        stage: "researching",
        hotness: "normal",
        nextAction: "Inserat prüfen",
        nextDue: "",
        contacts: [],
        notes: "Etablierte Garage am See. Stelle aktuell offen.",
      },
      {
        id: "seed-lead-karlgraf",
        company: "Karl Graf Automobile AG",
        role: "Automobil-Mechatroniker EFZ",
        link: "https://95339-hostingstorage-w1.s3-ch-west-1.mtfcloud.ch/customers/graf-auto/Automobil-Mechatroniker-EFZ.pdf",
        location: "Mettmenstetten — ~28 Min",
        salary: "",
        source: "grafauto.ch",
        favourite: false,
        priority: 2,
        stage: "researching",
        hotness: "normal",
        nextAction: "Stelleninserat (PDF) prüfen",
        nextDue: "",
        contacts: [],
        notes: "Aktuell offen: Mechatroniker EFZ (Inserat als PDF). Die Diagnostiker-Stelle ist nicht mehr ausgeschrieben.",
      },
      {
        id: "seed-lead-porsche-zug",
        company: "Porsche Zentrum Zug (Risch AG)",
        role: "Automobil-Mechatroniker (m/w/d)",
        link: "https://dealer.porsche.com/ch/zug/de-CH/wir-ueber-uns/jobs-und-karriere/automobil-mechatroniker-mwd",
        location: "Rotkreuz, ZG — ~35 Min",
        salary: "CHF 5'000–6'650 / Mt",
        source: "Porsche Zug",
        favourite: false,
        priority: 4,
        stage: "applied",
        hotness: "medium",
        nextAction: "Bewerbung warm halten — nachfassen",
        nextDue: "+7",
        contacts: [],
        notes: "Bereits beworben. Hochmargiges Porsche-Zentrum. Hinweis: Einarbeitung in Rotkreuz, danach fixe Stelle in Kriens (LU) ab Q4 2026.",
      },
      {
        id: "seed-lead-emilfreyracing",
        company: "Emil Frey Racing",
        role: "No. 2 Mechanic (Rennmechaniker) — Ferrari 296 GT3",
        link: "https://emilfreyracing.com",
        location: "Safenwil, AG — ~45 Min",
        salary: "€42k–60k (CHF-äquiv.)",
        source: "emilfreyracing.com",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "hot",
        nextAction: "Spontanbewerbung — AMG + Getriebe-Erfahrung betonen",
        nextDue: "",
        contacts: [],
        notes: "GT3 in DTM & GTWC. AMG-Motoren + Handschaltgetriebe übertragen sich direkt. Aktuell keine offenen Positionen (Stand 07/2026) — Spontanbewerbung bleibt der Weg.",
      },
      // --- Broader brand coverage (BMW / Ford / VW group) — added 2026-06-27 ---
      {
        id: "seed-lead-amag-kloten",
        company: "AMAG — Kloten",
        role: "Automobil Mechatroniker (m/w/d) 80-100%",
        link: "https://jobs.amag-group.ch/Automobil-Mechatroniker-mwd-80-100-de-j22930.html",
        location: "Kloten, ZH — ~20 Min",
        salary: "",
        source: "AMAG careers",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "normal",
        nextAction: "Inserat prüfen + bewerben",
        nextDue: "",
        contacts: [],
        notes: "AMAG-Standort Kloten (VW-Konzern). Strukturierte Ausbildung, intern Weg zur Porsche Academy.",
      },
      {
        id: "seed-lead-hedin-dielsdorf",
        company: "Hedin Automotive — Dielsdorf",
        role: "Automobilmechatroniker/-diagnostiker 100% (m/w/d)",
        link: "https://hedinautomotive.ch/stellenanzeigen/automobilmechatroniker-dielsdorf/",
        location: "Dielsdorf, ZH — ~18 Min",
        salary: "",
        source: "Hedin Automotive",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "medium",
        nextAction: "Bewerben — BMW/MINI, Diagnostiker-Anteil betonen",
        nextDue: "",
        contacts: [],
        notes: "BMW und MINI. Mechatroniker mit Diagnostiker-Anteil — passt zur Diagnostik-Laufbahn. Werks-Master-Technician-Ausbildung.",
      },
      {
        id: "seed-lead-hedin-samstagern",
        company: "Hedin Automotive — Samstagern",
        role: "Automobilmechatroniker 100% (m/w/d)",
        link: "https://hedinautomotive.ch/stellenanzeigen/automobilmechatroniker-100-m-w-d-3/",
        location: "Samstagern, ZH — ~28 Min",
        salary: "",
        source: "Hedin Automotive",
        favourite: false,
        priority: 2,
        stage: "researching",
        hotness: "medium",
        nextAction: "Prüfen — etwas weiter, aber Premium (BMW/MINI)",
        nextDue: "",
        contacts: [],
        notes: "BMW und MINI, Standort Samstagern. Etwas weiter weg, dafür Premium-Marke.",
      },
      {
        id: "seed-lead-thwilly-ford",
        company: "Th. Willy AG — Schlieren",
        role: "Automobil-Mechatroniker (w/m/d)",
        link: "https://thwilly.abacuscity.ch/de/job_1_100058",
        location: "Zürich-Schlieren — ~10 Min",
        salary: "",
        source: "Th. Willy / thwilly.ch",
        favourite: false,
        priority: 3,
        stage: "researching",
        hotness: "normal",
        nextAction: "Inserat prüfen + bewerben",
        nextDue: "",
        contacts: [],
        notes: "Ford (grösster der CH), MG, Cupra. Grosse Familiengruppe, Eintritt per sofort. Nahe (Schlieren).",
      },
    ],

    tasks: [
      // --- application set-up (original seed) ---
      {
        id: "seed-task-cv",
        title: "Finalise CV (DE + EN)",
        category: "setup",
        due: "+4",
        priority: "high",
        done: false,
        recurring: false,
        notes: "Use the Porsche version as the base. Keep AGVS + Mercedes HV/EV cert at the top.",
      },
      {
        id: "seed-task-ref",
        title: "Ask Merbag team lead for a reference letter",
        category: "network",
        due: "+6",
        priority: "high",
        done: false,
        recurring: false,
        notes: "",
      },
      {
        id: "seed-task-portfolio",
        title: "Build a short technical portfolio (AMG, gearbox, Xentry)",
        category: "setup",
        due: "+10",
        priority: "med",
        done: false,
        recurring: false,
        notes: "Photos / descriptions of AMG cylinder heads, gearbox rebuilds, an Xentry diagnostic workflow. Key for Porsche & motorsport applications.",
      },
      {
        id: "seed-task-linkedin",
        title: "Set up LinkedIn profile (HV/EV visible)",
        category: "setup",
        due: "+8",
        priority: "med",
        done: false,
        recurring: false,
        notes: "",
      },
      {
        id: "seed-task-hv",
        title: "Collect HV certificates as PDF",
        category: "admin",
        due: "+3",
        priority: "med",
        done: false,
        recurring: false,
        notes: "",
      },
      // --- Merbag / Herr Gut campaign + interview prep (added 2026-06-27) ---
      {
        id: "seed-task-gut-meeting",
        title: "Set up a meeting with Herr Gut (Merbag/Mercedes openings)",
        category: "network",
        due: "+3",
        priority: "high",
        done: false,
        recurring: false,
        notes: "Arrange it for NEXT WEEK. Ask Herr Gut about open positions at other Merbag / Mercedes locations — Merbag has many sites beyond yours.",
      },
      {
        id: "seed-task-gut-prep",
        title: "Prep for the Herr Gut meeting",
        category: "network",
        due: "+6",
        priority: "high",
        done: false,
        recurring: false,
        notes: "Before the meeting, line up: which positions are open (and where), how to apply for each, and what advice to ask for. Bring your CV + HV/AMG certs. Have 3–4 sharp questions ready and know which locations you'd move for.",
      },
      {
        id: "seed-task-merbag-contacts",
        title: "Get 3 more Merbag contacts this week",
        category: "network",
        due: "+6",
        priority: "high",
        done: false,
        recurring: true,
        notes: "Weekly goal: ask colleagues you work with at Merbag for names/intros — three new contacts every week until end of July 2026. After that you're on holiday, then you leave — so build the network NOW while you're still inside.",
      },
      {
        id: "seed-task-interview-practice",
        title: "Practice interview: experience, skills, motivation",
        category: "skill",
        due: "+7",
        priority: "med",
        done: false,
        recurring: true,
        notes: "Rehearse out loud (ideally with someone): describe your Merbag experience (AMG engines, HV/EV, Xentry diagnostics, gearbox work), your strongest skills, and what motivates you. Tighten it into a confident 60-second story.",
      },
    ],

    contacts: [
      {
        id: "seed-contact-merbag",
        name: "Merbag team lead",
        company: "Merbag AG",
        relationship: "Trainer / reference",
        intro: "Direct",
        notes: "Strongest reference — largest MB workshop in CH.",
        helpsWith: ["seed-lead-merbag-diag-schlieren", "seed-lead-emilfrey-diag"],
      },
      {
        id: "seed-contact-gut",
        name: "Herr Gut",
        company: "Merbag AG",
        relationship: "Manager / internal referral",
        intro: "Direct",
        notes: "Key internal contact — set up a meeting to ask about openings at other Merbag / Mercedes locations and how to apply.",
        helpsWith: ["seed-lead-merbag-diag-schlieren", "seed-lead-merbag-schlieren-nfz", "seed-lead-merbag-lastwagen"],
      },
    ],

    // Device-local defaults (theme/language/goal). Not synced.
    settings: { theme: "drift", dailyGoal: 3, name: "Ben", lang: "en", knownDevices: [] },
    meta: { xp: 0, streak: 0, bestStreak: 0, lastActiveDay: "" },
  };

  // Browser: self === window → window.PP_SEED. Node (ESM import): self is
  // undefined → globalThis.PP_SEED. One file, both worlds, no module syntax.
  const root = typeof self !== "undefined" ? self : globalThis;
  root.PP_SEED = SEED;
})();
